### ISSUE TITLE
Crash in Pyramide Level

### ISSUE THREAD

**Issue by sYnapZiX** [TonicGaro/TTSE-HD-Texture-Pack#1]
I downloaded the latest release of your Texture Pack, extracted it, copied it into the TTSE folder and synchronized it with Rayman Control Panel.

Up until the pyramid level (which is one of the last levels, the one where you have to turn into that mummy thing to enter the level) everything went perfectly fine without a single crash but the Pyramide Level is crashing every single time upon finishing the loading screen, right at the moment it should transition to the level.

Without the Texture Pack this doesnt happen. Of course i copied over the mem files as well and i even tried to edit them manually to double the amount of memory but to no success. I also have the compatibility patch, the fixes and the no-cd installed from the links in the forum. In DgVoodoo i also tried all possible combinations of settings including all VRAM settings.

My version of the Special Edition is 8.7.4 and i have downloaded it from the links in the forum.

Other than that i have to say that the texture pack looks nothing other then amazing!

**Comment by sYnapZiX** [comment]
I was just able to fix it. In case it crashes for anyone, go into the "GameData" folder and edit the "game.mem"

Double the following values:

PositionMemorySize(1000) -> (2000)
AIMemory(250000) -> (500000)
ACPMemory(5000000) -> (10000000)
GameLevelMemorySize(5500000) -> (11000000)

After doing that the level was able to load successfully.

**Comment by TonicGaro** [comment]
Lol yeah I didn't really test this texture pack too well, I think I heard about this bug in the TT Speedrunning Discord before but wasn't quite sure what caused it. Good job on finding the fix!
